Repository Ashraf-Alshashaa/TradeHub-Frontend, pull requests merged in 2024-06, with the labels that each got.

#6 Create product card
  src/components/image/Image.tsx
  src/components/image/types.ts
  src/components/product-card/Product-card.tsx
  src/components/product-card/product-card.css
  src/components/product-card/types.ts
  src/index.css
  src/main.tsx
  src/pages/Test.tsx
Labels: ready to merge

#11 Create footer
  src/components/Footer.tsx
  src/components/footer.css
  src/components/types.ts
  src/pages/Test.tsx
Labels: under review

#10 Create dropdown
  .gitignore
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/styles.css
  src/components/dropdown/types.ts
  src/index.css
  src/pages/Test.tsx
  src/types.ts
Labels: under review

#7 Create filter by component
  package-lock.json
  package.json
  src/components/filter-by/Filter-by.tsx
  src/components/filter-by/filter-by.css
  src/components/filter-by/types.ts
  src/pages/Test.tsx
Labels: not ready

#5 Create text input
  package-lock.json
  package.json
  src/components/text-input/Text-input.tsx
  src/components/text-input/types.ts
  src/index.css
  src/pages/Test.tsx
Labels: under review

#17 Created header
  src/components/header/Header.tsx
  src/components/header/styles.css
  src/components/header/types.ts
  src/pages/Test.tsx
Labels: under review

#22 Add logout and correct categories
  src/components/header/Header.tsx
  src/pages/products/Products.tsx
Labels: under review

#9 Initiated the radio button
  src/components/radio-button/Radio-button.tsx
  src/components/radio-button/radio-button.css
  src/components/radio-button/types.ts
  src/pages/Test.tsx
Labels: under review

#23 Create edit profile modal
  src/modals/Edit-profile.tsx
  src/pages/Test.tsx
  src/pages/user-profile/User-profile.tsx
Labels: under review

#26 Created textarea
  src/components/textarea/Textarea.tsx
  src/components/textarea/types.ts
  src/pages/Test.tsx
Labels: ready to merge

#25 Backend userprofile connection
  package-lock.json
  package.json
  src/app/store.ts
  src/components/product-card/Product-card.tsx
  src/components/product-card/types.ts
  src/components/product-listing/Product-listing.tsx
  src/components/product-listing/product-listing.css
  src/components/product-listing/types.ts
  src/features/addresses/addressSlice.ts
  src/features/addresses/types.ts
  src/features/auth/authSlice.ts
  src/features/products/productsSlice.ts
  src/features/products/types.ts
  src/features/users/types.ts
  src/features/users/userSlice.ts
  src/modals/Edit-profile.tsx
  src/pages/Test.tsx
  src/pages/products/Products.tsx
  src/pages/user-profile/Tab.tsx
  src/pages/user-profile/User-profile.tsx
  src/pages/user-profile/tab.css
  src/routes.tsx
Labels: ready to merge

#33 Fix dropdown
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/types.ts
  src/pages/Test.tsx
Labels: under review

#32 Fix textarea
  src/components/textarea/Textarea.tsx
  src/components/textarea/types.ts
Labels: under review

#34 Fix text input required
  src/components/text-input/Text-input.tsx
  src/components/text-input/types.ts
  src/pages/Test.tsx
Labels: ready to merge

#37 Added unique ID to radio buttons to connect the label to the button. …
  src/components/radio-button/Radio-button.tsx
  src/components/radio-button/radio-button.css
Labels: enhancement, under review

#30 Create edit profile modal
  src/axiosConfig.ts
  src/components/product-listing/Product-listing.tsx
  src/components/text-input/Text-input.tsx
  src/components/text-input/types.ts
  src/features/addresses/addressSlice.ts
  src/features/auth/authSlice.ts
  src/features/users/userSlice.ts
  src/modals/Change-password.tsx
  src/modals/Edit-profile.tsx
  src/pages/user-profile/User-profile.tsx
Labels: under review

#29 Create filter products
  src/app/store.ts
  src/components/filter-by/Filter-by.tsx
  src/components/filter-by/filter-by.css
  src/components/filter-by/types.ts
  src/features/categories/categorySlice.tsx
  src/features/categories/types.ts
  src/features/pricerange/priceRangeSlice.ts
  src/features/pricerange/types.ts
  src/features/products/productsSlice.ts
  src/pages/Login/Login.tsx
  src/pages/Test.tsx
  src/pages/products/Products.tsx
Labels: ready to merge

#27 Create product page
  src/app/store.ts
  src/components/product-card/Product-card.tsx
  src/components/product-card/types.ts
  src/components/radio-button/radio-button.css
  src/components/radio-button/types.ts
  src/components/text-input/Text-input.tsx
  src/components/text-input/types.ts
  src/features/auth/authSlice.ts
  src/features/bids/bidSlice.ts
  src/features/bids/types.ts
  src/features/products/productsSlice.ts
  src/features/products/types.ts
  src/modals/Choose-bid.tsx
  src/modals/types.ts
  src/pages/Test.tsx
  src/pages/product/Product.tsx
  src/pages/product/styles.css
  src/pages/products/Products.tsx
  src/routes.tsx
Labels: under review

#31 Create Edit/Add Product modal
  src/components/header/Header.tsx
  src/features/products/productsSlice.ts
  src/features/products/types.ts
  src/modals/Add-product.tsx
  src/modals/Edit-product.tsx
  src/modals/types.ts
  src/pages/Test.tsx
  src/pages/product/Product.tsx
Labels: under review
