Repository Ashraf-Alshashaa/TradeHub-Frontend, pull requests merged in 2024-07, with the labels that each got.

#39 Fix favicon and title
  index.html
  public/favicon.ico
  public/vite.svg
Labels: ready to merge

#38 Create cart modal
  src/app/store.ts
  src/components/header/Header.tsx
  src/components/product-listing/Product-listing.tsx
  src/components/product-listing/product-listing.css
  src/components/product-listing/types.ts
  src/features/payments/paymentSlice.ts
  src/features/payments/types.ts
  src/features/products/types.ts
  src/modals/Cart.tsx
  src/pages/Payment/Payment.tsx
  src/routes.tsx
Labels: ready to merge

#43 Created upload img component
  .gitignore
  index.html
  src/components/cloudinary-upload-widget/CloudinaryUploadWidget.tsx
  src/components/cloudinary-upload-widget/types.ts
  src/pages/Test.tsx
Labels: under review

#44 fixed My Listings and Sold Items
  src/features/products/productsSlice.ts
  src/pages/user-profile/Tab.tsx
Labels: under review

#45 added image upload in Edit/Add product
  src/components/product-card/product-card.css
  src/modals/Add-product.tsx
  src/modals/Edit-product.tsx
Labels: under review

#48 Added seller_city (location) to product cards
  src/components/product-card/Product-card.tsx
  src/components/product-card/types.ts
  src/features/products/types.ts
  src/pages/products/Products.tsx
Labels: under review

#49 Fix style
  src/App.css
  src/components/filter-by/Filter-by.tsx
  src/components/filter-by/filter-by.css
  src/components/header/Header.tsx
  src/components/header/styles.css
  src/components/radio-button/Radio-button.tsx
  src/components/radio-button/radio-button.css
  src/components/radio-button/types.ts
  src/pages/product/Product.tsx
  src/pages/product/styles.css
Labels: under review

#51 Fix address of newly registered user
  src/features/addresses/addressSlice.ts
  src/modals/Edit-profile.tsx
  src/pages/user-profile/User-profile.tsx
Labels: under review

#50 Created dashboard
  package-lock.json
  package.json
  src/app/store.ts
  src/features/reports/reportsSlice.ts
  src/features/reports/types.ts
  src/pages/Login/Login.tsx
  src/pages/dashboard/BidsReports.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/SalesReports.tsx
  src/pages/dashboard/styles.css
  src/pages/dashboard/types.ts
  src/routes.tsx
Labels: under review

#52 Fix refresh products
  src/components/filter-by/Filter-by.tsx
  src/components/header/Header.tsx
  src/pages/Login/Login.tsx
  src/pages/products/Products.tsx
  src/pages/user-profile/User-profile.tsx
Labels: not ready

#54 Fix choose bid button
  src/features/products/types.ts
  src/modals/Choose-bid.tsx
  src/pages/product/Product.tsx
Labels: under review

#42 Create websocket connection
  src/app/store.ts
  src/components/header/Header.tsx
  src/components/notification/Notification.tsx
  src/components/notification/NotificationContainer.tsx
  src/features/notification/notificationSlice.ts
  src/features/websocket/websocket.ts
  src/pages/Test.tsx
  src/pages/product/Product.tsx
  src/pages/products/Products.tsx
  src/pages/user-profile/User-profile.tsx
Labels: ready to merge

#59 Fixed Add Product
  src/components/text-input/Text-input.tsx
Labels: ready to merge
